version: '3'
services: 
    app: 
        build: .
        volumes:
            - ./:/app
        working_dir: /app
    server:
        image: nginx
        ports: 
            - 8000:80
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d
    bd: 
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_DATABASE=prueba
        volumes:
            - symfony-data:/var/lib/mysql


    
volumes:
    symfony-data:
